export const CONFIG = {
  HORIZONS: [30, 90, 365] as const,
  TOP_N: 100,
  MIN_TRADES: 20,
  MIN_VOLUME_USD: 100,
  OUTLIER_TRADE_FRACTION: 0.7,
  SKILL_WEIGHTS: {
    pctReturn: 0.5,
    winRate: 0.25,
    drawdown: 0.15,
    sampleSize: 0.1
  },
  DRAWDOWN_PENALTY_THRESHOLD: 0.2,
  BOT: {
    MAX_TRADES_PER_DAY: 50,
    MAX_SIMULTANEOUS_MARKETS: 30,
    MIN_AVG_TRADE_SIZE_USD: 1
  },
  POLYMARKET_API_BASE: process.env.POLYMARKET_API_BASE ?? "https://data-api.polymarket.com",
  SEED_WALLET_COUNT: 500,
  API_RETRIES: 5,
  RETRY_BASE_DELAY_MS: 1000,
  WALLET_BATCH_SIZE: 5,
  BATCH_DELAY_MS: 250,
  MIN_REQUEST_INTERVAL_MS: 150,
  ACTIVITY_LIMIT: 500,
  CLOSED_POSITION_PAGE_SIZE: 50,
  MAX_CLOSED_POSITION_PAGES: 40,
  LEADERBOARD_PAGE_SIZE: 50,
  TRADES_DISCOVERY_LIMIT: 10000,
  SECONDS_PER_DAY: 86400,
  MS_PER_SECOND: 1000
};

export type HorizonDays = (typeof CONFIG.HORIZONS)[number];
